name: Fail On Not Timeout
on: [push]
jobs:
  failure_job:
    runs-on: ubuntu-latest
    name: A job that fails
    steps:
      - uses: actions/checkout@v2
      - name: Run file with timeout
        id: longrunner
        continue-on-error: true
        timeout-minutes: 1 # Times out after 1 minute
        run: "[ 'fail' == 'succeed' ] || echo '::set-output name=failure_reason::Script failed due to something random'" # Set your output error if your script fails. Include useful message
      - name: check previuos step on failure only
        if: failure()
        run: "[ -n '${{ steps.longrunner.outputs.failure_reason }}' ] && echo '::error::${{ steps.longrunner.outputs.failure_reason }}' && exit 1"
      - name: continue to do more stuff
        run: echo "I did more stuff"