name: Succeed On Timeout
on: [push]
jobs:
  succeed_job:
    runs-on: ubuntu-latest
    name: A job that succeeds
    steps:
      - uses: actions/checkout@v2
      - name: Run file with timeout
        id: longrunner
        continue-on-error: true
        timeout-minutes: 1 # Times out after 1 minute
        # We add the echo \r so that we remov ethe previuos ::error:: written by the timeout
        run: sleep 90 && echo -en "\r" || echo '::set-output name=failure_reason::Script failed due to something random' # Set your output error if your script fails. Include useful message
      - name: check previuos step
        run: "[ -n '${{ steps.longrunner.outputs.failure_reason }}' ] && echo '::error::${{ steps.longrunner.outputs.failure_reason }}' && exit 1 || echo ''"
      - name: continue to do more stuff
        run: echo "I did more stuff"