name: Timeout example
on: [push]
jobs:
  success_job:
    runs-on: ubuntu-latest
    name: A cool job
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: no timeout
        run: timeout 10 python ./sleep.py || if [[ $? != 124 && $? != 0 ]]; then exit $?; fi
      - name: timeout # We add or so that return code is not none-zero which causes pipeline to fail
        run: timeout 1 python ./sleep.py || if [[ $? != 124 && $? != 0 ]]; then exit $?; fi